repos: 
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks
        language: system
        args: [ "protect", "--staged", "--verbose" ]
      - id: prevent-commits-to-default-branch
        name: prevent commits to default branch
        entry: prevent-commits-to-default-branch.sh
        language: script
